### ISSUE TITLE
Error @line 411in CloudNetController.py

### ISSUE THREAD

**Issue by grenadier-amit** [dedousis/CloudnetController#1]
Task <Timer/tid7> caused exception and was de-scheduled
Traceback (most recent call last):
  File "/home/karma/pox/pox/lib/recoco/recoco.py", line 276, in cycle
    rv = t.execute()
  File "/home/karma/pox/pox/lib/recoco/recoco.py", line 94, in execute
    return self.gen.send(v)
  File "/home/karma/pox/pox/lib/recoco/recoco.py", line 751, in run
    rv = self._callback(*self._args,**self._kw)
  File "/home/karma/pox/CloudNetController.py", line 411, in handle_migration
    (new_mac, new_dpid, new_inport) = self.arpmap[self.old_migrated_IPs[old_IP]]
KeyError: IPAddr('10.0.0.5')

**Comment by grenadier-amit** [comment]
Initial pingall command solved the issue.
